version: "3.9"
services:
  yt-dlp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'downloader'
    volumes:
      - videos:/home/deploy/videos
    env_file:
      - .env
    command: sh ./script.sh

volumes:
  videos:
