version: "3.9"
services:
  yt-dlp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'downloader'
    volumes:
      - videos:/home/deploy/videos
    env_file:
      - .env
    command: sh ./scripts/bulk-download

volumes:
  videos:
    driver: value
    driver_opts:
        size: 20G
