version: "3.9"
services:
  yt-dlp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'downloader'
    volumes:
      - videos:/home/deploy/videos
    command: >
      yt-dlp --format 'bv*[height<=1080]+wa' \
        --output '/home/deploy/videos/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' \
        --batch '.playlist'
        --limit-rate '5M'

volumes:
  videos:
