version: "3.9"
services:
  yt-dlp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'downloader'
    env_file:
      - .env
    volumes:
      - ${DOWNLOAD}:/home/deploy/videos
    command: sh ./scripts/bulk-download
