#!/usr/bin/env bash

  yt-dlp \
    --format="bv*[height<=${HEIGHT}]+wa" \
    --output="/home/deploy/videos/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" \
    --limit-rate=$RATE_LIMIT \
    --extractor-args=$EXTRACTOR_ARGS \
    --concurrent-fragments=$FRAGMENTS \
    --merge-output-format=$FORMATS \
    --batch-file=$PLAYLIST
